//------------------ Generated by Oche ------------------
//              Don't edit this file by hand!
// ------------------------------------------------------
// ABI hash: 00001505
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;
import 'dart:collection';
import 'dart:typed_data' as typed_data;
import 'dart:typed_data';
import 'package:ffi/ffi.dart';

final String _libName = Platform.isWindows ? 'libolib.dll' : (Platform.isMacOS ? 'libolib.dylib' : 'libolib.so');
final dynlib = ffi.DynamicLibrary.open('./$_libName');
final _ocheFree = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer), void Function(ffi.Pointer)>('ocheFree');
final _ocheFreeDeep = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer), void Function(ffi.Pointer)>('ocheFreeDeep');
final _ocheFreeInner = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer, ffi.Int32), void Function(ffi.Pointer, int)>('ocheFreeInner');
final _ocheStrAlloc = dynlib.lookupFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>), ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>)>('ocheStrAlloc');
final _ocheStrFree = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer<ffi.Void>), void Function(ffi.Pointer<ffi.Void>)>('ocheStrFree');
final _ocheGetError = dynlib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('ocheGetError');
void _checkError() { final ptr = _ocheGetError(); if (ptr.address != 0) { final msg = ptr.toDartString(); _ocheFree(ptr); throw Exception('NimError: $msg'); } }
const _ocheExpectedAbiHash = '00001505';
String _ocheLibAbiHash() {
  try {
    final fn = dynlib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('ocheAbiHash');
    return fn().toDartString();
  } catch (_) { return ''; }
}
void _ocheCheckAbi() {
  final libHash = _ocheLibAbiHash();
  if (libHash.isNotEmpty && libHash != _ocheExpectedAbiHash) {
    throw StateError('Oche ABI mismatch: .so was compiled with hash \$libHash but bindings expect 00001505. Recompile Nim and regenerate bindings.');
  }
}
final _abiChecked = () { _ocheCheckAbi(); return true; }();


enum Status {
  Pending,
  Active,
  Closed,
}

enum Color {
  Red,
  Green,
  Blue,
}
final class NPoint extends ffi.Struct {
  @ffi.Double() external double x;
  @ffi.Double() external double y;
}

extension type PointView(NPoint _ref) {
  double get x => _ref.x;
  set x(double v) => _ref.x = v;
  double get y => _ref.y;
  set y(double v) => _ref.y = v;
  void _packInto(ffi.Pointer<NPoint> p) {
    p.ref.x = _ref.x;
    p.ref.y = _ref.y;
  }
  Point freeze() => Point(
      x: _ref.x,
      y: _ref.y,
    );
}

class Point {
  double x;
  double y;
  Point({
    required this.x,
    required this.y
  });

  void _pack(NPoint target, ffi.Allocator alloc) {
    target.x = x;
    target.y = y;
  }

  void _packManual(NPoint target) {
    target.x = x;
    target.y = y;
  }

  static Point _unpack(NPoint source) {
    return Point(
    x: source.x,
    y: source.y,
    );
  }
}
final class NTagged extends ffi.Struct {
  external NPoint point;
  external ffi.Pointer<Utf8> label;
}

extension type TaggedView(NTagged _ref) {
  PointView get point => PointView(_ref.point);
  String get label => (_ref.label.address == 0) ? '' : _ref.label.toDartString();
  set label(String v) {
    if (_ref.label.address != 0) _ocheStrFree(_ref.label.cast());
    _ref.label = v.isEmpty ? ffi.nullptr : _ocheStrAlloc(v.toNativeUtf8(allocator: malloc)).cast();
  }
  void _packInto(ffi.Pointer<NTagged> p) {
    p.ref.point = _ref.point;
    p.ref.label = _ref.label;
  }
  Tagged freeze() => Tagged(
      point: PointView(_ref.point).freeze(),
      label: (_ref.label.address == 0) ? '' : _ref.label.toDartString(),
    );
}

class Tagged {
  Point point;
  String label;
  Tagged({
    required this.point,
    required this.label
  });

  void _pack(NTagged target, ffi.Allocator alloc) {
    this.point._pack(target.point, alloc);
    target.label = label.toNativeUtf8(allocator: alloc);
  }

  void _packManual(NTagged target) {
    this.point._pack(target.point, malloc);
    target.label = label.toNativeUtf8(allocator: malloc);
  }

  static Tagged _unpack(NTagged source) {
    return Tagged(
    point: Point._unpack(source.point),
    label: (source.label.address == 0) ? '' : source.label.toDartString(),
    );
  }
}
final class NParticle extends ffi.Struct {
  @ffi.Double() external double x;
  @ffi.Double() external double y;
  @ffi.Double() external double mass;
  @ffi.Int32() external int color;
}

extension type ParticleView(NParticle _ref) {
  double get x => _ref.x;
  set x(double v) => _ref.x = v;
  double get y => _ref.y;
  set y(double v) => _ref.y = v;
  double get mass => _ref.mass;
  set mass(double v) => _ref.mass = v;
  Color get color => Color.values[_ref.color];
  set color(Color v) => _ref.color = v.index;
  void _packInto(ffi.Pointer<NParticle> p) {
    p.ref.x = _ref.x;
    p.ref.y = _ref.y;
    p.ref.mass = _ref.mass;
    p.ref.color = _ref.color;
  }
  Particle freeze() => Particle(
      x: _ref.x,
      y: _ref.y,
      mass: _ref.mass,
      color: Color.values[_ref.color],
    );
}

class Particle {
  double x;
  double y;
  double mass;
  Color color;
  Particle({
    required this.x,
    required this.y,
    required this.mass,
    required this.color
  });

  void _pack(NParticle target, ffi.Allocator alloc) {
    target.x = x;
    target.y = y;
    target.mass = mass;
    target.color = color.index;
  }

  void _packManual(NParticle target) {
    target.x = x;
    target.y = y;
    target.mass = mass;
    target.color = color.index;
  }

  static Particle _unpack(NParticle source) {
    return Particle(
    x: source.x,
    y: source.y,
    mass: source.mass,
    color: Color.values[source.color],
    );
  }
}
final class NUser extends ffi.Struct {
  external ffi.Pointer<Utf8> name;
  @ffi.Int64() external int age;
  @ffi.Int32() external int status;
}

extension type UserView(NUser _ref) {
  String get name => (_ref.name.address == 0) ? '' : _ref.name.toDartString();
  set name(String v) {
    if (_ref.name.address != 0) _ocheStrFree(_ref.name.cast());
    _ref.name = v.isEmpty ? ffi.nullptr : _ocheStrAlloc(v.toNativeUtf8(allocator: malloc)).cast();
  }
  int get age => _ref.age;
  set age(int v) => _ref.age = v;
  Status get status => Status.values[_ref.status];
  set status(Status v) => _ref.status = v.index;
  void _packInto(ffi.Pointer<NUser> p) {
    p.ref.name = _ref.name;
    p.ref.age = _ref.age;
    p.ref.status = _ref.status;
  }
  User freeze() => User(
      name: (_ref.name.address == 0) ? '' : _ref.name.toDartString(),
      age: _ref.age,
      status: Status.values[_ref.status],
    );
}

class User {
  String name;
  int age;
  Status status;
  User({
    required this.name,
    required this.age,
    required this.status
  });

  void _pack(NUser target, ffi.Allocator alloc) {
    target.name = name.toNativeUtf8(allocator: alloc);
    target.age = age;
    target.status = status.index;
  }

  void _packManual(NUser target) {
    target.name = name.toNativeUtf8(allocator: malloc);
    target.age = age;
    target.status = status.index;
  }

  static User _unpack(NUser source) {
    return User(
    name: (source.name.address == 0) ? '' : source.name.toDartString(),
    age: source.age,
    status: Status.values[source.status],
    );
  }
}
typedef NmakePointN = ffi.Pointer<NPoint> Function(ffi.Double, ffi.Double);
typedef NmakePointD = ffi.Pointer<NPoint> Function(double, double);
typedef NmakeUserN = ffi.Pointer<NUser> Function(ffi.Pointer<Utf8>, ffi.Int64);
typedef NmakeUserD = ffi.Pointer<NUser> Function(ffi.Pointer<Utf8>, int);
typedef NmakeTaggedN = ffi.Pointer<NTagged> Function(ffi.Pointer<Utf8>, ffi.Double, ffi.Double);
typedef NmakeTaggedD = ffi.Pointer<NTagged> Function(ffi.Pointer<Utf8>, double, double);
typedef NmakeParticleN = ffi.Pointer<NParticle> Function(ffi.Double, ffi.Double, ffi.Double, ffi.Int32);
typedef NmakeParticleD = ffi.Pointer<NParticle> Function(double, double, double, int);
typedef NgetColorN = ffi.Int32 Function();
typedef NgetColorD = int Function();
typedef NgetStatusN = ffi.Int32 Function(ffi.Pointer<NUser>);
typedef NgetStatusD = int Function(ffi.Pointer<NUser>);
typedef NaddPointsN = ffi.Pointer<NPoint> Function(ffi.Pointer<NPoint>, ffi.Pointer<NPoint>);
typedef NaddPointsD = ffi.Pointer<NPoint> Function(ffi.Pointer<NPoint>, ffi.Pointer<NPoint>);
typedef NgreetUserN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<NUser>);
typedef NgreetUserD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<NUser>);
typedef NmaybePointN = ffi.Pointer<ffi.Void> Function(ffi.Bool);
typedef NmaybePointD = ffi.Pointer<ffi.Void> Function(bool);
typedef NmaybeUserN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>);
typedef NmaybeUserD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>);
typedef NaddIntsN = ffi.Int64 Function(ffi.Int64, ffi.Int64);
typedef NaddIntsD = int Function(int, int);
typedef NmulFloatN = ffi.Double Function(ffi.Double, ffi.Double);
typedef NmulFloatD = double Function(double, double);
typedef NechoStrN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>);
typedef NechoStrD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<Utf8>);
typedef NsumSeqN = ffi.Int64 Function(ffi.Pointer<ffi.Int64>, ffi.Int64);
typedef NsumSeqD = int Function(ffi.Pointer<ffi.Int64>, int);
typedef NmakePointListN = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef NmakePointListD = ffi.Pointer<ffi.Void> Function(int);
typedef NmakeUserListN = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef NmakeUserListD = ffi.Pointer<ffi.Void> Function(int);
typedef NgetPointsViewN = ffi.Pointer<ffi.Void> Function();
typedef NgetPointsViewD = ffi.Pointer<ffi.Void> Function();
typedef NgetUsersViewN = ffi.Pointer<ffi.Void> Function();
typedef NgetUsersViewD = ffi.Pointer<ffi.Void> Function();
typedef NmakeIntBufferN = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef NmakeIntBufferD = ffi.Pointer<ffi.Void> Function(int);
typedef NmakeParticleBufferN = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef NmakeParticleBufferD = ffi.Pointer<ffi.Void> Function(int);
typedef NmakeUserBufferN = ffi.Pointer<ffi.Void> Function(ffi.Int64);
typedef NmakeUserBufferD = ffi.Pointer<ffi.Void> Function(int);
typedef NsumIntBufferN = ffi.Int64 Function(ffi.Pointer<ffi.Void>);
typedef NsumIntBufferD = int Function(ffi.Pointer<ffi.Void>);
typedef NdoubleIntBufferN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>);
typedef NdoubleIntBufferD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>);
typedef NcountActiveUsersN = ffi.Int64 Function(ffi.Pointer<ffi.Void>);
typedef NcountActiveUsersD = int Function(ffi.Pointer<ffi.Void>);
typedef NmultiplyArrayN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Double>, ffi.Int64, ffi.Double);
typedef NmultiplyArrayD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Double>, int, double);
typedef NdotProductN = ffi.Double Function(ffi.Pointer<ffi.Double>, ffi.Int64, ffi.Pointer<ffi.Double>, ffi.Int64);
typedef NdotProductD = double Function(ffi.Pointer<ffi.Double>, int, ffi.Pointer<ffi.Double>, int);
typedef NsumIntsPtrN = ffi.Int64 Function(ffi.Pointer<ffi.Int64>, ffi.Int64);
typedef NsumIntsPtrD = int Function(ffi.Pointer<ffi.Int64>, int);
typedef NnegateIntsPtrN = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Int64>, ffi.Int64);
typedef NnegateIntsPtrD = ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Int64>, int);
typedef NriskyDivideN = ffi.Int64 Function(ffi.Int64, ffi.Int64);
typedef NriskyDivideD = int Function(int, int);
typedef NriskyUserN = ffi.Pointer<NUser> Function(ffi.Pointer<Utf8>);
typedef NriskyUserD = ffi.Pointer<NUser> Function(ffi.Pointer<Utf8>);
typedef NresetPointN = ffi.Pointer<NPoint> Function(ffi.Pointer<NPoint>);
typedef NresetPointD = ffi.Pointer<NPoint> Function(ffi.Pointer<NPoint>);
final _finalizerDeep = Finalizer<ffi.Pointer<ffi.Void>>((ptr) => _ocheFreeDeep(ptr));

abstract class OcheView<T> extends ListBase<T> {
  ffi.Pointer<ffi.Void> get _nativePtr;
  @override int get length;
  @override set length(int value) => throw UnsupportedError('Cannot resize native buffer');
  @override Iterator<T> get iterator => _NativeListIterator<T>(this);
}

class NativeListView<T> extends OcheView<T> {
  ffi.Pointer<ffi.Void> _ptr;
  final T Function(ffi.Pointer<ffi.Void> ptr) _unpacker;
  final int _elemSize;
  @override late final int length;
  NativeListView(this._ptr, this._unpacker, this._elemSize) {
    if (_ptr.address == 0) { length = 0; return; }
    length = ffi.Pointer<ffi.Int64>.fromAddress(_ptr.address).value;
    _finalizerDeep.attach(this, _ptr, detach: this);
  }
  @override ffi.Pointer<ffi.Void> get _nativePtr => _ptr;
  @override T operator [](int index) {
    if (_ptr.address == 0) throw StateError('NativeListView has been freed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    return _unpacker(ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize)));
  }
  @override void operator []=(int index, T value) => throw UnsupportedError('View mode is read-only. Use Buffer mode for mutation.');
  void free() {
    if (_ptr.address == 0) return;
    _finalizerDeep.detach(this);
    _ocheFreeDeep(_ptr);
    _ptr = ffi.Pointer.fromAddress(0);
  }
}

class SharedListView<T> extends OcheView<T> {
  ffi.Pointer<ffi.Void> _ptr;
  final T Function(ffi.Pointer<ffi.Void> ptr) _unpacker;
  final void Function(ffi.Pointer<ffi.Void> ptr, dynamic value)? _packer;
  final int _elemSize;
  @override late final int length;
  SharedListView(this._ptr, this._unpacker, this._packer, this._elemSize) {
    if (_ptr.address == 0) { length = 0; return; }
    length = ffi.Pointer<ffi.Int64>.fromAddress(_ptr.address).value;
    _finalizerDeep.attach(this, _ptr, detach: this);
  }
  @override ffi.Pointer<ffi.Void> get _nativePtr => _ptr;
  @override T operator [](int index) {
    if (_ptr.address == 0) throw StateError('SharedListView has been freed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    return _unpacker(ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize)));
  }
  @override void operator []=(int index, dynamic value) {
    if (_ptr.address == 0) throw StateError('SharedListView has been freed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    final flags = ffi.Pointer<ffi.Int32>.fromAddress(_ptr.address + 12).value;
    if ((flags & 1) != 0) throw StateError('Buffer is frozen (READ-ONLY)');
    final p = ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize));
    if (_packer != null) { _packer!(p, value); }
    else if (value is int) { ffi.Pointer<ffi.Int64>.fromAddress(p.address).value = value; }
    else if (value is double) { ffi.Pointer<ffi.Double>.fromAddress(p.address).value = value; }
    else if (value is bool) { ffi.Pointer<ffi.Bool>.fromAddress(p.address).value = value; }
    else { throw UnsupportedError('Mutation via []= not supported for this type.'); }
  }
  typed_data.TypedData? toTypedData() {
    if (_ptr.address == 0) return null;
    final dataAddr = _ptr.address + 16;
    if (_elemSize == 8) return ffi.Pointer<ffi.Int64>.fromAddress(dataAddr).asTypedList(length);
    if (_elemSize == 4) return ffi.Pointer<ffi.Int32>.fromAddress(dataAddr).asTypedList(length);
    if (_elemSize == 2) return ffi.Pointer<ffi.Int16>.fromAddress(dataAddr).asTypedList(length);
    if (_elemSize == 1) return ffi.Pointer<ffi.Uint8>.fromAddress(dataAddr).asTypedList(length);
    return null;
  }
  void free() {
    if (_ptr.address == 0) return;
    _finalizerDeep.detach(this);
    _ocheFreeDeep(_ptr);
    _ptr = ffi.Pointer.fromAddress(0);
  }
}

class _NativeListIterator<T> implements Iterator<T> {
  final OcheView<T> _view; int _index = -1;
  _NativeListIterator(this._view);
  @override T get current => _view[_index];
  @override bool moveNext() => ++_index < _view.length;
}
class Oche {
  late final nmakePointCall = dynlib.lookupFunction<NmakePointN, NmakePointD>('makePoint');

  Point makePoint(final double v_x, final double v_y) {
      final p = nmakePointCall(v_x, v_y); _checkError();
      try { return Point._unpack(p.ref); } finally { _ocheFree(p); }
  }
  late final nmakeUserCall = dynlib.lookupFunction<NmakeUserN, NmakeUserD>('makeUser');

  User makeUser(final String v_name, final int v_age) {
    return using((alloc) {

      final p = nmakeUserCall(v_name.toNativeUtf8(allocator: alloc), v_age); _checkError();
      try { return User._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }
  late final nmakeTaggedCall = dynlib.lookupFunction<NmakeTaggedN, NmakeTaggedD>('makeTagged');

  Tagged makeTagged(final String v_label, final double v_x, final double v_y) {
    return using((alloc) {

      final p = nmakeTaggedCall(v_label.toNativeUtf8(allocator: alloc), v_x, v_y); _checkError();
      try { return Tagged._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }
  late final nmakeParticleCall = dynlib.lookupFunction<NmakeParticleN, NmakeParticleD>('makeParticle');

  Particle makeParticle(final double v_x, final double v_y, final double v_mass, final Color v_color) {
      final p = nmakeParticleCall(v_x, v_y, v_mass, v_color.index); _checkError();
      try { return Particle._unpack(p.ref); } finally { _ocheFree(p); }
  }
  late final ngetColorCall = dynlib.lookupFunction<NgetColorN, NgetColorD>('getColor');

  Color getColor() {
      final r = ngetColorCall(); _checkError();
      return Color.values[r];
  }
  late final ngetStatusCall = dynlib.lookupFunction<NgetStatusN, NgetStatusD>('getStatus');

  Status getStatus(final dynamic v_u) {
    return using((alloc) {
    final _v_uPtr = alloc.allocate<NUser>(ffi.sizeOf<NUser>());
    if (v_u is UserView) { v_u._packInto(_v_uPtr); } else { (v_u as User)._pack(_v_uPtr.ref, alloc); }
      final r = ngetStatusCall(_v_uPtr); _checkError();
      return Status.values[r];
    });
  }
  late final naddPointsCall = dynlib.lookupFunction<NaddPointsN, NaddPointsD>('addPoints');

  Point addPoints(final dynamic v_a, final dynamic v_b) {
    return using((alloc) {
    final _v_aPtr = alloc.allocate<NPoint>(ffi.sizeOf<NPoint>());
    if (v_a is PointView) { v_a._packInto(_v_aPtr); } else { (v_a as Point)._pack(_v_aPtr.ref, alloc); }
    final _v_bPtr = alloc.allocate<NPoint>(ffi.sizeOf<NPoint>());
    if (v_b is PointView) { v_b._packInto(_v_bPtr); } else { (v_b as Point)._pack(_v_bPtr.ref, alloc); }
      final p = naddPointsCall(_v_aPtr, _v_bPtr); _checkError();
      try { return Point._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }
  late final ngreetUserCall = dynlib.lookupFunction<NgreetUserN, NgreetUserD>('greetUser');

  String greetUser(final dynamic v_u) {
    return using((alloc) {
    final _v_uPtr = alloc.allocate<NUser>(ffi.sizeOf<NUser>());
    if (v_u is UserView) { v_u._packInto(_v_uPtr); } else { (v_u as User)._pack(_v_uPtr.ref, alloc); }
      final p = ngreetUserCall(_v_uPtr); _checkError();
      if (p.address == 0) return ''; try { return p.cast<Utf8>().toDartString(); } finally { _ocheFree(p); }
    });
  }
  late final nmaybePointCall = dynlib.lookupFunction<NmaybePointN, NmaybePointD>('maybePoint');

  Point? maybePoint(final bool v_give) {
      final p = nmaybePointCall(v_give); _checkError();
      if (p.address == 0) return null; try {
        return Point._unpack(p.cast<NPoint>().ref);
      } finally { _ocheFree(p); }
  }
  late final nmaybeUserCall = dynlib.lookupFunction<NmaybeUserN, NmaybeUserD>('maybeUser');

  User? maybeUser(final String v_name) {
    return using((alloc) {

      final p = nmaybeUserCall(v_name.toNativeUtf8(allocator: alloc)); _checkError();
      if (p.address == 0) return null; try {
        return User._unpack(p.cast<NUser>().ref);
      } finally { _ocheFree(p); }
    });
  }
  late final naddIntsCall = dynlib.lookupFunction<NaddIntsN, NaddIntsD>('addInts');

  int addInts(final int v_a, final int v_b) {
      final r = naddIntsCall(v_a, v_b); _checkError();
      return r;
  }
  late final nmulFloatCall = dynlib.lookupFunction<NmulFloatN, NmulFloatD>('mulFloat');

  double mulFloat(final double v_a, final double v_b) {
      final r = nmulFloatCall(v_a, v_b); _checkError();
      return r;
  }
  late final nechoStrCall = dynlib.lookupFunction<NechoStrN, NechoStrD>('echoStr');

  String echoStr(final String v_s) {
    return using((alloc) {

      final p = nechoStrCall(v_s.toNativeUtf8(allocator: alloc)); _checkError();
      if (p.address == 0) return ''; try { return p.cast<Utf8>().toDartString(); } finally { _ocheFree(p); }
    });
  }
  late final nsumSeqCall = dynlib.lookupFunction<NsumSeqN, NsumSeqD>('sumSeq');

  int sumSeq(final List<int> v_values) {
    return using((alloc) {
    final _v_valuesPtr = alloc.allocate<ffi.Int64>(v_values.length * ffi.sizeOf<ffi.Int64>());
    for (var i = 0; i < v_values.length; i++) { _v_valuesPtr[i] = v_values[i]; }
      final r = nsumSeqCall(_v_valuesPtr, v_values.length); _checkError();
      return r;
    });
  }
  late final nmakePointListCall = dynlib.lookupFunction<NmakePointListN, NmakePointListD>('makePointList');

  List<Point> makePointList(final int v_n) {
      final p = nmakePointListCall(v_n); _checkError();
      if (p.address == 0) return []; try {
        final L = ffi.Pointer<ffi.Int64>.fromAddress(p.address).value; final d = ffi.Pointer<NPoint>.fromAddress(p.address + 16);
        return List<Point>.generate(L, (i) => Point._unpack(d[i]));
      } finally { _ocheFreeDeep(p); }
  }
  late final nmakeUserListCall = dynlib.lookupFunction<NmakeUserListN, NmakeUserListD>('makeUserList');

  List<User> makeUserList(final int v_n) {
      final p = nmakeUserListCall(v_n); _checkError();
      if (p.address == 0) return []; try {
        final L = ffi.Pointer<ffi.Int64>.fromAddress(p.address).value; final d = ffi.Pointer<NUser>.fromAddress(p.address + 16);
        return List<User>.generate(L, (i) => User._unpack(d[i]));
      } finally { _ocheFreeDeep(p); }
  }
  late final ngetPointsViewCall = dynlib.lookupFunction<NgetPointsViewN, NgetPointsViewD>('getPointsView');

  NativeListView<PointView> getPointsView() {
      final p = ngetPointsViewCall(); _checkError();
      return NativeListView<PointView>(p, (ptr) => PointView(ptr.cast<NPoint>().ref), ffi.sizeOf<NPoint>());
  }
  late final ngetUsersViewCall = dynlib.lookupFunction<NgetUsersViewN, NgetUsersViewD>('getUsersView');

  NativeListView<UserView> getUsersView() {
      final p = ngetUsersViewCall(); _checkError();
      return NativeListView<UserView>(p, (ptr) => UserView(ptr.cast<NUser>().ref), ffi.sizeOf<NUser>());
  }
  late final nmakeIntBufferCall = dynlib.lookupFunction<NmakeIntBufferN, NmakeIntBufferD>('makeIntBuffer');

  SharedListView<int> makeIntBuffer(final int v_n) {
      final p = nmakeIntBufferCall(v_n); _checkError();
      return SharedListView<int>(p, (ptr) => ptr.cast<ffi.Int64>().value, (p, v) { p.cast<ffi.Int64>().value = v as int; }, ffi.sizeOf<ffi.Int64>());
  }
  late final nmakeParticleBufferCall = dynlib.lookupFunction<NmakeParticleBufferN, NmakeParticleBufferD>('makeParticleBuffer');

  SharedListView<ParticleView> makeParticleBuffer(final int v_n) {
      final p = nmakeParticleBufferCall(v_n); _checkError();
      return SharedListView<ParticleView>(p, (ptr) => ParticleView(ptr.cast<NParticle>().ref), (p, v) { if (v is Particle) { v._packManual(p.cast<NParticle>().ref); } else if (v is ParticleView) { v._packInto(p.cast<NParticle>()); } }, ffi.sizeOf<NParticle>());
  }
  late final nmakeUserBufferCall = dynlib.lookupFunction<NmakeUserBufferN, NmakeUserBufferD>('makeUserBuffer');

  SharedListView<UserView> makeUserBuffer(final int v_n) {
      final p = nmakeUserBufferCall(v_n); _checkError();
      return SharedListView<UserView>(p, (ptr) => UserView(ptr.cast<NUser>().ref), (p, v) { if (v is User) { _ocheFreeInner(p, 3); v._packManual(p.cast<NUser>().ref); } else if (v is UserView) { v._packInto(p.cast<NUser>()); } }, ffi.sizeOf<NUser>());
  }
  late final nsumIntBufferCall = dynlib.lookupFunction<NsumIntBufferN, NsumIntBufferD>('sumIntBuffer');

  int sumIntBuffer(final SharedListView<int> v_buf) {
      final r = nsumIntBufferCall(v_buf._nativePtr); _checkError();
      return r;
  }
  late final ndoubleIntBufferCall = dynlib.lookupFunction<NdoubleIntBufferN, NdoubleIntBufferD>('doubleIntBuffer');

  SharedListView<int> doubleIntBuffer(final SharedListView<int> v_buf) {
      final p = ndoubleIntBufferCall(v_buf._nativePtr); _checkError();
      return SharedListView<int>(p, (ptr) => ptr.cast<ffi.Int64>().value, (p, v) { p.cast<ffi.Int64>().value = v as int; }, ffi.sizeOf<ffi.Int64>());
  }
  late final ncountActiveUsersCall = dynlib.lookupFunction<NcountActiveUsersN, NcountActiveUsersD>('countActiveUsers');

  int countActiveUsers(final SharedListView<UserView> v_buf) {
      final r = ncountActiveUsersCall(v_buf._nativePtr); _checkError();
      return r;
  }
  late final nmultiplyArrayCall = dynlib.lookupFunction<NmultiplyArrayN, NmultiplyArrayD>('multiplyArray');

  SharedListView<double> multiplyArray(final typed_data.Float64List v_arr, final double v_factor) {
    return using((alloc) {
    final _v_arrPtr = alloc.allocate<ffi.Double>(v_arr.length * ffi.sizeOf<ffi.Double>());
    _v_arrPtr.asTypedList(v_arr.length).setAll(0, v_arr);
      final p = nmultiplyArrayCall(_v_arrPtr, v_arr.length, v_factor); _checkError();
      return SharedListView<double>(p, (ptr) => ptr.cast<ffi.Double>().value, (p, v) { p.cast<ffi.Double>().value = v as double; }, ffi.sizeOf<ffi.Double>());
    });
  }
  late final ndotProductCall = dynlib.lookupFunction<NdotProductN, NdotProductD>('dotProduct');

  double dotProduct(final typed_data.Float64List v_a, final typed_data.Float64List v_b) {
    return using((alloc) {
    final _v_aPtr = alloc.allocate<ffi.Double>(v_a.length * ffi.sizeOf<ffi.Double>());
    _v_aPtr.asTypedList(v_a.length).setAll(0, v_a);
    final _v_bPtr = alloc.allocate<ffi.Double>(v_b.length * ffi.sizeOf<ffi.Double>());
    _v_bPtr.asTypedList(v_b.length).setAll(0, v_b);
      final r = ndotProductCall(_v_aPtr, v_a.length, _v_bPtr, v_b.length); _checkError();
      return r;
    });
  }
  late final nsumIntsPtrCall = dynlib.lookupFunction<NsumIntsPtrN, NsumIntsPtrD>('sumIntsPtr');

  int sumIntsPtr(final ffi.Pointer<ffi.Int64> v_arr, final int v_arr_len) {
      final r = nsumIntsPtrCall(v_arr, v_arr_len); _checkError();
      return r;
  }
  late final nnegateIntsPtrCall = dynlib.lookupFunction<NnegateIntsPtrN, NnegateIntsPtrD>('negateIntsPtr');

  SharedListView<int> negateIntsPtr(final ffi.Pointer<ffi.Int64> v_arr, final int v_arr_len) {
      final p = nnegateIntsPtrCall(v_arr, v_arr_len); _checkError();
      return SharedListView<int>(p, (ptr) => ptr.cast<ffi.Int64>().value, (p, v) { p.cast<ffi.Int64>().value = v as int; }, ffi.sizeOf<ffi.Int64>());
  }
  late final nriskyDivideCall = dynlib.lookupFunction<NriskyDivideN, NriskyDivideD>('riskyDivide');

  int riskyDivide(final int v_a, final int v_b) {
      final r = nriskyDivideCall(v_a, v_b); _checkError();
      return r;
  }
  late final nriskyUserCall = dynlib.lookupFunction<NriskyUserN, NriskyUserD>('riskyUser');

  User riskyUser(final String v_name) {
    return using((alloc) {

      final p = nriskyUserCall(v_name.toNativeUtf8(allocator: alloc)); _checkError();
      try { return User._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }
  late final nresetPointCall = dynlib.lookupFunction<NresetPointN, NresetPointD>('resetPoint');

  Point resetPoint(final dynamic v_p) {
    return using((alloc) {
    final _v_pPtr = alloc.allocate<NPoint>(ffi.sizeOf<NPoint>());
    if (v_p is PointView) { v_p._packInto(_v_pPtr); } else { (v_p as Point)._pack(_v_pPtr.ref, alloc); }
      final p = nresetPointCall(_v_pPtr); _checkError();
      try { return Point._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }

}
final oche = Oche();

extension makeIntBufferExt on SharedListView<int> {
  /// Zero-copy typed view into Nim RAM. Returns null if buffer is freed.
  Int64List? toInt64List() {
    if (_nativePtr.address == 0) return null;
    return ffi.Pointer<ffi.Int64>.fromAddress(_nativePtr.address + 16).asTypedList(length);
  }
}
extension doubleIntBufferExt on SharedListView<int> {
  /// Zero-copy typed view into Nim RAM. Returns null if buffer is freed.
  Int64List? toInt64List() {
    if (_nativePtr.address == 0) return null;
    return ffi.Pointer<ffi.Int64>.fromAddress(_nativePtr.address + 16).asTypedList(length);
  }
}
extension multiplyArrayExt on SharedListView<double> {
  /// Zero-copy typed view into Nim RAM. Returns null if buffer is freed.
  Float64List? toFloat64List() {
    if (_nativePtr.address == 0) return null;
    return ffi.Pointer<ffi.Double>.fromAddress(_nativePtr.address + 16).asTypedList(length);
  }
}
extension negateIntsPtrExt on SharedListView<int> {
  /// Zero-copy typed view into Nim RAM. Returns null if buffer is freed.
  Int64List? toInt64List() {
    if (_nativePtr.address == 0) return null;
    return ffi.Pointer<ffi.Int64>.fromAddress(_nativePtr.address + 16).asTypedList(length);
  }
}
