# ------------------ Generated by Porche ------------------
#              Don't edit this file by hand!
# -----------------------------------------------------------
# ABI hash: 00001505
from typing import Optional, Any, List, Union
import ctypes
import os

try:
  import numpy as np
  _HAS_NUMPY = True
except ImportError:
  _HAS_NUMPY = False

_struct_size_cache: dict = {}
_struct_types: dict = {}
_struct_field_meta: dict = {}

def _struct_size(name: str) -> int:
  return _struct_size_cache.get(name, 8)

# -- Copy-mode helpers --

def _pack_struct(name: str, obj):
  if obj is None: return None
  t = _struct_types[name]
  if hasattr(obj, '_as_buffer'): return obj
  buf = t()
  # XxxView — memcpy entire struct buffer directly (fast path)
  if hasattr(obj, '_addr'):
    ctypes.memmove(ctypes.addressof(buf), obj._addr, ctypes.sizeof(t))
    return buf
  meta = _struct_field_meta.get(name, {})
  # Xxx plain class or dict — iterate fields
  pairs = list(obj.items()) if hasattr(obj, 'items') else [(k, getattr(obj,k)) for k in getattr(obj, '__slots__', [])]
  for (k, v) in pairs:
    kind, extra = meta.get(k, ('pod', None))
    if kind == 'struct':
      if v is None:
        pass  # leave zeroed
      elif hasattr(v, '_addr'):
        # XxxView — memcpy into the nested field slot
        sub_t = _struct_types[extra]
        ctypes.memmove(ctypes.addressof(getattr(buf, k)), v._addr, ctypes.sizeof(sub_t))
      elif isinstance(v, dict):
        setattr(buf, k, _pack_struct(extra, v))
      else:
        setattr(buf, k, v)  # already a ctypes struct instance
    elif kind == 'string':
      setattr(buf, k, _lib.ocheStrAlloc(v.encode('utf-8')) if v else 0)
    elif kind == 'enum':
      setattr(buf, k, int(v))
    else:
      setattr(buf, k, v)
  return buf

def _struct_copy(name: str, ptr, offset: int, elem_size: int, index: int) -> dict:
  addr = ctypes.cast(ptr, ctypes.c_void_p).value + offset + index * elem_size
  return _struct_from_ctypes(name, _struct_types[name].from_address(addr))

_struct_view_types: dict = {}
_struct_plain_types: dict = {}

def _struct_copy_view(name: str, ptr, offset: int, elem_size: int, index: int):
  src = ctypes.cast(ptr, ctypes.c_void_p).value + offset + index * elem_size
  dst = _lib.ocheAllocBytes(ctypes.c_size_t(elem_size))
  ctypes.memmove(dst, src, elem_size)
  view_cls = _struct_view_types.get(name)
  return view_cls(dst, owned=True) if view_cls else None

def _struct_unpack_plain(name: str, ptr, offset: int, elem_size: int, index: int):
  addr = ctypes.cast(ptr, ctypes.c_void_p).value + offset + index * elem_size
  ct = _struct_types[name].from_address(addr)
  meta = _struct_field_meta[name]
  plain_cls = _struct_plain_types[name]
  kwargs = {}
  for fn, _ in ct._fields_:
    raw = getattr(ct, fn)
    kind, extra = meta.get(fn, ('pod', None))
    if kind == 'string':
      kwargs[fn] = ctypes.string_at(raw).decode('utf-8') if raw else None
    elif kind == 'struct':
      sv = _struct_view_types[extra](ctypes.addressof(getattr(ct, fn)), owned=False)
      kwargs[fn] = _struct_plain_types[extra]._from_view(sv)
    else:
      kwargs[fn] = raw
  return plain_cls(**kwargs)

def _struct_from_ctypes(name: str, c) -> dict:
  d = {}
  meta = _struct_field_meta.get(name, {})
  for (fname, _) in c._fields_:
    raw = getattr(c, fname)
    kind, extra = meta.get(fname, ('pod', None))
    if kind == 'string':
      d[fname] = ctypes.string_at(raw).decode('utf-8') if raw else None
    elif kind == 'struct':
      d[fname] = _struct_from_ctypes(extra, raw)
    else:
      d[fname] = raw
  return d

# -- NativeListView (view mode: zero-copy, read-only) --

class NativeListView:
  __slots__ = ('_ptr', '_n', '_elem_size', '_unpacker', '_free_fn', '_elem_ctype', '_numpy_dtype')
  def __init__(self, ptr, unpacker, elem_size: int, free_fn, elem_ctype=None, numpy_dtype=None):
    self._ptr = ptr
    self._n = ctypes.cast(ptr, ctypes.POINTER(ctypes.c_int64)).contents.value if ptr else 0
    self._elem_size = elem_size
    self._unpacker = unpacker
    self._free_fn = free_fn
    self._elem_ctype = getattr(ctypes, elem_ctype) if isinstance(elem_ctype, str) else elem_ctype
    self._numpy_dtype = numpy_dtype
  def __len__(self): return self._n
  def _get_one(self, i: int):
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker: return self._unpacker(addr)
    return ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value
  def __getitem__(self, key):
    if isinstance(key, slice):
      return [self._get_one(i) for i in range(*key.indices(self._n))]
    i = key if key >= 0 else self._n + key
    if i < 0 or i >= self._n: raise IndexError(f'NativeListView index {key} out of range (len={self._n})')
    return self._get_one(i)
  def __setitem__(self, i, v):
    raise TypeError('NativeListView is read-only. Use SharedListView for mutation.')
  def __iter__(self):
    for i in range(self._n): yield self._get_one(i)
  def __reversed__(self):
    for i in range(self._n - 1, -1, -1): yield self._get_one(i)
  def __contains__(self, v): return any(x == v for x in self)
  def __repr__(self): return f'NativeListView(len={self._n})'
  def __del__(self):
    if self._ptr and self._free_fn: self._free_fn(self._ptr)
  def index(self, v, start=0, stop=None):
    stop = self._n if stop is None else min(stop, self._n)
    for i in range(start, stop):
      if self._get_one(i) == v: return i
    raise ValueError(f'{v!r} is not in NativeListView')
  def count(self, v): return sum(1 for x in self if x == v)
  def to_list(self) -> list:
    return [self._get_one(i) for i in range(self._n)]
  def to_numpy(self):
    if not _HAS_NUMPY: return None
    data_addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16
    raw = (ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr)
    if self._numpy_dtype is not None:
      # POD struct — read-only copy (Nim may free the buffer anytime)
      return np.frombuffer(raw, dtype=self._numpy_dtype, count=self._n).copy()
    elif self._elem_ctype is not None:
      return np.frombuffer(raw, dtype=np.dtype(self._elem_ctype), count=self._n).copy()
    return None

# -- SharedListView (share mode: zero-copy, read-write) --

class SharedListView:
  __slots__ = ('_ptr', '_n', '_elem_size', '_unpacker', '_type_id', '_is_pod', '_elem_ctype', '_numpy_dtype')
  def __init__(self, ptr, n: int, elem_size: int, unpacker, type_id: int = 0,
               is_pod: bool = True, elem_ctype=None, numpy_dtype=None):
    self._ptr = ptr
    self._n = n
    self._elem_size = elem_size
    self._unpacker = unpacker
    self._type_id = type_id
    self._is_pod = is_pod
    self._elem_ctype = getattr(ctypes, elem_ctype) if isinstance(elem_ctype, str) else elem_ctype
    self._numpy_dtype = numpy_dtype
  def __len__(self): return self._n
  def _get_one(self, i: int):
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker: return self._unpacker(addr)
    return ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value
  def _set_one(self, i: int, v):
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker:
      if not self._is_pod: _ocheFreeInner(ctypes.c_void_p(addr), self._type_id)
      if hasattr(v, '_addr'):
        ctypes.memmove(addr, v._addr, self._elem_size)
      else:
        struct_name = None
        for sn, st in _struct_types.items():
          if ctypes.sizeof(st) == self._elem_size: struct_name = sn; break
        if struct_name is None:
          raise TypeError(f'Cannot infer struct type for SharedListView elem_size={self._elem_size}')
        buf = _pack_struct(struct_name, v)
        ctypes.memmove(addr, ctypes.addressof(buf), self._elem_size)
    else:
      ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value = v
  def __getitem__(self, key):
    if isinstance(key, slice):
      return [self._get_one(i) for i in range(*key.indices(self._n))]
    i = key if key >= 0 else self._n + key
    if i < 0 or i >= self._n: raise IndexError(f'SharedListView index {key} out of range (len={self._n})')
    return self._get_one(i)
  def __setitem__(self, key, v):
    if isinstance(key, slice):
      indices = range(*key.indices(self._n))
      values = list(v)
      if len(indices) != len(values): raise ValueError('slice assignment length mismatch')
      for i, val in zip(indices, values): self._set_one(i, val)
      return
    i = key if key >= 0 else self._n + key
    if i < 0 or i >= self._n: raise IndexError(f'SharedListView index {key} out of range (len={self._n})')
    self._set_one(i, v)
  def __iter__(self):
    for i in range(self._n): yield self._get_one(i)
  def __reversed__(self):
    for i in range(self._n - 1, -1, -1): yield self._get_one(i)
  def __contains__(self, v): return any(x == v for x in self)
  def __repr__(self): return f'SharedListView(len={self._n})'
  def index(self, v, start=0, stop=None):
    stop = self._n if stop is None else min(stop, self._n)
    for i in range(start, stop):
      if self._get_one(i) == v: return i
    raise ValueError(f'{v!r} is not in SharedListView')
  def count(self, v): return sum(1 for x in self if x == v)
  def to_list(self) -> list:
    return [self._get_one(i) for i in range(self._n)]
  def free(self):
    if self._ptr:
      _lib.ocheFreeDeep(self._ptr)
      self._ptr = None
      self._n = 0
  def __del__(self): self.free()  # GC safety net — explicit .free() preferred
  def __enter__(self): return self
  def __exit__(self, *_): self.free()
  def to_numpy(self):
    if not _HAS_NUMPY: return None
    data_addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16
    raw = (ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr)
    if self._numpy_dtype is not None:
      # POD struct — zero-copy writable view directly into Nim RAM
      return np.frombuffer(raw, dtype=self._numpy_dtype, count=self._n)
    elif self._elem_ctype is not None:
      # primitive — zero-copy writable view directly into Nim RAM
      return np.frombuffer(raw, dtype=np.dtype(self._elem_ctype), count=self._n)
    return None

_lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'libolib.so')
_lib = ctypes.CDLL(_lib_path)

_lib.ocheFree.argtypes = [ctypes.c_void_p]
_lib.ocheFree.restype = None
_lib.ocheFreeDeep.argtypes = [ctypes.c_void_p]
_lib.ocheFreeDeep.restype = None
_ocheFreeInner = _lib.ocheFreeInner
_ocheFreeInner.argtypes = [ctypes.c_void_p, ctypes.c_int32]
_ocheFreeInner.restype = None
_lib.ocheAllocBytes.argtypes = [ctypes.c_size_t]
_lib.ocheAllocBytes.restype = ctypes.c_void_p
_lib.ocheStrAlloc.argtypes = [ctypes.c_char_p]
_lib.ocheStrAlloc.restype = ctypes.c_void_p
_lib.ocheStrFree.argtypes = [ctypes.c_void_p]
_lib.ocheStrFree.restype = None
_oche_get_error = _lib.ocheGetError
_oche_get_error.restype = ctypes.c_void_p
def _check_error():
    p = _oche_get_error()
    if p is not None:
        msg = ctypes.string_at(p).decode('utf-8')
        _lib.ocheFree(p)
        raise RuntimeError('NimError: ' + msg)

_OCHE_EXPECTED_ABI_HASH = '00001505'
try:
    _abi_fn = _lib.ocheAbiHash
    _abi_fn.restype = ctypes.c_char_p
    _lib_hash = _abi_fn().decode('utf-8')
    if _lib_hash and _lib_hash != _OCHE_EXPECTED_ABI_HASH:
        raise RuntimeError(
            f'Oche ABI mismatch: .so was compiled with hash {_lib_hash!r} '
            f'but bindings expect {_OCHE_EXPECTED_ABI_HASH!r}. '
            'Recompile Nim and regenerate bindings.')
except AttributeError:
    pass  # older .so without ocheAbiHash — skip check

class Point_t(ctypes.Structure):
  _fields_ = [
    ('x', ctypes.c_double),
    ('y', ctypes.c_double),
  ]
_struct_size_cache['Point'] = ctypes.sizeof(Point_t)
_struct_types['Point'] = Point_t
_struct_field_meta['Point'] = {
  'x': ('pod', None),
  'y': ('pod', None),
}
_OFF_Point_x = Point_t.x.offset
_OFF_Point_y = Point_t.y.offset
class PointView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def x(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Point_x).value
  @x.setter
  def x(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Point_x).value = v
  @property
  def y(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Point_y).value
  @y.setter
  def y(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Point_y).value = v
  def __eq__(self, other) -> bool:
    if isinstance(other, PointView): return self._addr == other._addr or self.to_dict() == other.to_dict()
    if isinstance(other, Point): return self.to_dict() == other.__dict__ if hasattr(other, '__dict__') else all(getattr(other, k, None) == v for k, v in self.to_dict().items())
    return NotImplemented
  def __hash__(self): return hash(tuple(self.to_dict().values()))
  def to_dict(self) -> dict:
    return _struct_from_ctypes('Point', Point_t.from_address(self._addr))
  def freeze(self) -> 'Point':
    return Point._from_view(self)
  def __repr__(self):
    return 'PointView(' + str(self.to_dict()) + ')'
_struct_view_types['Point'] = PointView
class Point:
  __slots__ = ('x', 'y')
  def __init__(self, x=None, y=None):
    self.x = x
    self.y = y
  @staticmethod
  def _from_view(v: 'PointView') -> 'Point':
    return Point(x=v.x, y=v.y)
  def __repr__(self):
    return 'Point(' + ', '.join(f'{k}={getattr(self,k)!r}' for k in self.__slots__) + ')'
_struct_plain_types['Point'] = Point
_NUMPY_DTYPE_Point = np.dtype([
  ('x', 'f8'),
  ('y', 'f8'),
]) if _HAS_NUMPY else None

class Tagged_t(ctypes.Structure):
  _fields_ = [
    ('point', Point_t),
    ('label', ctypes.c_void_p),
  ]
_struct_size_cache['Tagged'] = ctypes.sizeof(Tagged_t)
_struct_types['Tagged'] = Tagged_t
_struct_field_meta['Tagged'] = {
  'point': ('struct', 'Point'),
  'label': ('string', None),
}
_OFF_Tagged_point = Tagged_t.point.offset
_OFF_Tagged_label = Tagged_t.label.offset
class TaggedView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _p = ctypes.c_void_p.from_address(self._addr + _OFF_Tagged_label).value
      if _p: _lib.ocheStrFree(ctypes.c_void_p(_p))
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def point(self) -> 'PointView':
    return PointView(self._addr + _OFF_Tagged_point, owned=False)
  @property
  def label(self) -> Optional[str]:
    p = ctypes.c_void_p.from_address(self._addr + _OFF_Tagged_label).value
    return ctypes.string_at(p).decode('utf-8') if p else None
  @label.setter
  def label(self, v: Optional[str]):
    old = ctypes.c_void_p.from_address(self._addr + _OFF_Tagged_label).value
    if old: _lib.ocheStrFree(ctypes.c_void_p(old))
    new_p = _lib.ocheStrAlloc(v.encode('utf-8')) if v is not None else 0
    ctypes.c_void_p.from_address(self._addr + _OFF_Tagged_label).value = new_p
  def __eq__(self, other) -> bool:
    if isinstance(other, TaggedView): return self._addr == other._addr or self.to_dict() == other.to_dict()
    if isinstance(other, Tagged): return self.to_dict() == other.__dict__ if hasattr(other, '__dict__') else all(getattr(other, k, None) == v for k, v in self.to_dict().items())
    return NotImplemented
  def __hash__(self): return hash(tuple(self.to_dict().values()))
  def to_dict(self) -> dict:
    return _struct_from_ctypes('Tagged', Tagged_t.from_address(self._addr))
  def freeze(self) -> 'Tagged':
    return Tagged._from_view(self)
  def __repr__(self):
    return 'TaggedView(' + str(self.to_dict()) + ')'
_struct_view_types['Tagged'] = TaggedView
class Tagged:
  __slots__ = ('point', 'label')
  def __init__(self, point=None, label=None):
    self.point = point
    self.label = label
  @staticmethod
  def _from_view(v: 'TaggedView') -> 'Tagged':
    return Tagged(point=Point._from_view(v.point), label=v.label)
  def __repr__(self):
    return 'Tagged(' + ', '.join(f'{k}={getattr(self,k)!r}' for k in self.__slots__) + ')'
_struct_plain_types['Tagged'] = Tagged
_NUMPY_DTYPE_Tagged = None  # not POD (has strings/pointers)

class Particle_t(ctypes.Structure):
  _fields_ = [
    ('x', ctypes.c_double),
    ('y', ctypes.c_double),
    ('mass', ctypes.c_double),
    ('color', ctypes.c_int32),
  ]
_struct_size_cache['Particle'] = ctypes.sizeof(Particle_t)
_struct_types['Particle'] = Particle_t
_struct_field_meta['Particle'] = {
  'x': ('pod', None),
  'y': ('pod', None),
  'mass': ('pod', None),
  'color': ('enum', None),
}
_OFF_Particle_x = Particle_t.x.offset
_OFF_Particle_y = Particle_t.y.offset
_OFF_Particle_mass = Particle_t.mass.offset
_OFF_Particle_color = Particle_t.color.offset
class ParticleView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def x(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Particle_x).value
  @x.setter
  def x(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Particle_x).value = v
  @property
  def y(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Particle_y).value
  @y.setter
  def y(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Particle_y).value = v
  @property
  def mass(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Particle_mass).value
  @mass.setter
  def mass(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Particle_mass).value = v
  @property
  def color(self) -> int:
    return ctypes.c_int32.from_address(self._addr + _OFF_Particle_color).value
  @color.setter
  def color(self, v: int):
    ctypes.c_int32.from_address(self._addr + _OFF_Particle_color).value = int(v)
  def __eq__(self, other) -> bool:
    if isinstance(other, ParticleView): return self._addr == other._addr or self.to_dict() == other.to_dict()
    if isinstance(other, Particle): return self.to_dict() == other.__dict__ if hasattr(other, '__dict__') else all(getattr(other, k, None) == v for k, v in self.to_dict().items())
    return NotImplemented
  def __hash__(self): return hash(tuple(self.to_dict().values()))
  def to_dict(self) -> dict:
    return _struct_from_ctypes('Particle', Particle_t.from_address(self._addr))
  def freeze(self) -> 'Particle':
    return Particle._from_view(self)
  def __repr__(self):
    return 'ParticleView(' + str(self.to_dict()) + ')'
_struct_view_types['Particle'] = ParticleView
class Particle:
  __slots__ = ('x', 'y', 'mass', 'color')
  def __init__(self, x=None, y=None, mass=None, color=None):
    self.x = x
    self.y = y
    self.mass = mass
    self.color = color
  @staticmethod
  def _from_view(v: 'ParticleView') -> 'Particle':
    return Particle(x=v.x, y=v.y, mass=v.mass, color=v.color)
  def __repr__(self):
    return 'Particle(' + ', '.join(f'{k}={getattr(self,k)!r}' for k in self.__slots__) + ')'
_struct_plain_types['Particle'] = Particle
_NUMPY_DTYPE_Particle = np.dtype([
  ('x', 'f8'),
  ('y', 'f8'),
  ('mass', 'f8'),
  ('color', 'i4'),
]) if _HAS_NUMPY else None

class User_t(ctypes.Structure):
  _fields_ = [
    ('name', ctypes.c_void_p),
    ('age', ctypes.c_int64),
    ('status', ctypes.c_int32),
  ]
_struct_size_cache['User'] = ctypes.sizeof(User_t)
_struct_types['User'] = User_t
_struct_field_meta['User'] = {
  'name': ('string', None),
  'age': ('pod', None),
  'status': ('enum', None),
}
_OFF_User_name = User_t.name.offset
_OFF_User_age = User_t.age.offset
_OFF_User_status = User_t.status.offset
class UserView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _p = ctypes.c_void_p.from_address(self._addr + _OFF_User_name).value
      if _p: _lib.ocheStrFree(ctypes.c_void_p(_p))
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def name(self) -> Optional[str]:
    p = ctypes.c_void_p.from_address(self._addr + _OFF_User_name).value
    return ctypes.string_at(p).decode('utf-8') if p else None
  @name.setter
  def name(self, v: Optional[str]):
    old = ctypes.c_void_p.from_address(self._addr + _OFF_User_name).value
    if old: _lib.ocheStrFree(ctypes.c_void_p(old))
    new_p = _lib.ocheStrAlloc(v.encode('utf-8')) if v is not None else 0
    ctypes.c_void_p.from_address(self._addr + _OFF_User_name).value = new_p
  @property
  def age(self) -> int:
    return ctypes.c_int64.from_address(self._addr + _OFF_User_age).value
  @age.setter
  def age(self, v: int):
    ctypes.c_int64.from_address(self._addr + _OFF_User_age).value = v
  @property
  def status(self) -> int:
    return ctypes.c_int32.from_address(self._addr + _OFF_User_status).value
  @status.setter
  def status(self, v: int):
    ctypes.c_int32.from_address(self._addr + _OFF_User_status).value = int(v)
  def __eq__(self, other) -> bool:
    if isinstance(other, UserView): return self._addr == other._addr or self.to_dict() == other.to_dict()
    if isinstance(other, User): return self.to_dict() == other.__dict__ if hasattr(other, '__dict__') else all(getattr(other, k, None) == v for k, v in self.to_dict().items())
    return NotImplemented
  def __hash__(self): return hash(tuple(self.to_dict().values()))
  def to_dict(self) -> dict:
    return _struct_from_ctypes('User', User_t.from_address(self._addr))
  def freeze(self) -> 'User':
    return User._from_view(self)
  def __repr__(self):
    return 'UserView(' + str(self.to_dict()) + ')'
_struct_view_types['User'] = UserView
class User:
  __slots__ = ('name', 'age', 'status')
  def __init__(self, name=None, age=None, status=None):
    self.name = name
    self.age = age
    self.status = status
  @staticmethod
  def _from_view(v: 'UserView') -> 'User':
    return User(name=v.name, age=v.age, status=v.status)
  def __repr__(self):
    return 'User(' + ', '.join(f'{k}={getattr(self,k)!r}' for k in self.__slots__) + ')'
_struct_plain_types['User'] = User
_NUMPY_DTYPE_User = None  # not POD (has strings/pointers)

class Status:
  Pending = 0
  Active = 1
  Closed = 2

class Color:
  Red = 0
  Green = 1
  Blue = 2

class Porche:
  _makePoint = _lib.makePoint
  _makePoint.argtypes = [ctypes.c_double, ctypes.c_double]
  _makePoint.restype = ctypes.c_void_p
  def makePoint(self, x: float, y: float) -> 'Point':
    r = self._makePoint(x, y)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['Point']
    _ct = _struct_types['Point'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['Point']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _makeUser = _lib.makeUser
  _makeUser.argtypes = [ctypes.c_char_p, ctypes.c_int64]
  _makeUser.restype = ctypes.c_void_p
  def makeUser(self, name: str, age: int) -> 'User':
    r = self._makeUser(name.encode('utf-8') if name else None, age)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['User']
    _ct = _struct_types['User'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['User']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _makeTagged = _lib.makeTagged
  _makeTagged.argtypes = [ctypes.c_char_p, ctypes.c_double, ctypes.c_double]
  _makeTagged.restype = ctypes.c_void_p
  def makeTagged(self, label: str, x: float, y: float) -> 'Tagged':
    r = self._makeTagged(label.encode('utf-8') if label else None, x, y)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['Tagged']
    _ct = _struct_types['Tagged'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['Tagged']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _makeParticle = _lib.makeParticle
  _makeParticle.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_int32]
  _makeParticle.restype = ctypes.c_void_p
  def makeParticle(self, x: float, y: float, mass: float, color: Any) -> 'Particle':
    r = self._makeParticle(x, y, mass, int(color))
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['Particle']
    _ct = _struct_types['Particle'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['Particle']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _getColor = _lib.getColor
  _getColor.argtypes = []
  _getColor.restype = ctypes.c_int32
  def getColor(self, ) -> int:
    r = self._getColor()
    _check_error()
    return r

  _getStatus = _lib.getStatus
  _getStatus.argtypes = [ctypes.c_void_p]
  _getStatus.restype = ctypes.c_int32
  def getStatus(self, u: Union['User', 'UserView']) -> int:
    u_buf = _pack_struct('User', u) if u is not None else None
    r = self._getStatus(ctypes.byref(u_buf) if u_buf is not None else None)
    _check_error()
    return r

  _addPoints = _lib.addPoints
  _addPoints.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
  _addPoints.restype = ctypes.c_void_p
  def addPoints(self, a: Union['Point', 'PointView'], b: Union['Point', 'PointView']) -> 'Point':
    a_buf = _pack_struct('Point', a) if a is not None else None
    b_buf = _pack_struct('Point', b) if b is not None else None
    r = self._addPoints(ctypes.byref(a_buf) if a_buf is not None else None, ctypes.byref(b_buf) if b_buf is not None else None)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['Point']
    _ct = _struct_types['Point'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['Point']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _greetUser = _lib.greetUser
  _greetUser.argtypes = [ctypes.c_void_p]
  _greetUser.restype = ctypes.c_void_p
  def greetUser(self, u: Union['User', 'UserView']) -> str:
    u_buf = _pack_struct('User', u) if u is not None else None
    r = self._greetUser(ctypes.byref(u_buf) if u_buf is not None else None)
    _check_error()
    if r is None: return ''
    s = ctypes.string_at(r).decode('utf-8'); _lib.ocheFree(r); return s

  _maybePoint = _lib.maybePoint
  _maybePoint.argtypes = [ctypes.c_bool]
  _maybePoint.restype = ctypes.c_void_p
  def maybePoint(self, give: bool) -> Optional[Union['Point', 'PointView']]:
    r = self._maybePoint(give)
    _check_error()
    if r is None: return None
    sz = _struct_size('Point')
    out = _struct_unpack_plain('Point', r, 0, sz, 0); _lib.ocheFree(r); return out

  _maybeUser = _lib.maybeUser
  _maybeUser.argtypes = [ctypes.c_char_p]
  _maybeUser.restype = ctypes.c_void_p
  def maybeUser(self, name: str) -> Optional[Union['User', 'UserView']]:
    r = self._maybeUser(name.encode('utf-8') if name else None)
    _check_error()
    if r is None: return None
    sz = _struct_size('User')
    out = _struct_unpack_plain('User', r, 0, sz, 0); _lib.ocheFree(r); return out

  _addInts = _lib.addInts
  _addInts.argtypes = [ctypes.c_int64, ctypes.c_int64]
  _addInts.restype = ctypes.c_int64
  def addInts(self, a: int, b: int) -> int:
    r = self._addInts(a, b)
    _check_error()
    return r

  _mulFloat = _lib.mulFloat
  _mulFloat.argtypes = [ctypes.c_double, ctypes.c_double]
  _mulFloat.restype = ctypes.c_double
  def mulFloat(self, a: float, b: float) -> float:
    r = self._mulFloat(a, b)
    _check_error()
    return r

  _echoStr = _lib.echoStr
  _echoStr.argtypes = [ctypes.c_char_p]
  _echoStr.restype = ctypes.c_void_p
  def echoStr(self, s: str) -> str:
    r = self._echoStr(s.encode('utf-8') if s else None)
    _check_error()
    if r is None: return ''
    s = ctypes.string_at(r).decode('utf-8'); _lib.ocheFree(r); return s

  _sumSeq = _lib.sumSeq
  _sumSeq.argtypes = [ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
  _sumSeq.restype = ctypes.c_int64
  def sumSeq(self, values: List[Any]) -> int:
    if _HAS_NUMPY and isinstance(values, np.ndarray) and values.dtype == np.dtype('i8') and values.data.contiguous:
      values_ptr = values.ctypes.data_as(ctypes.POINTER(ctypes.c_int64))
      values_len = len(values)
    elif hasattr(values, 'buffer_info'):
      _buf_ptr, _buf_len = values.buffer_info()
      values_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_int64))
      values_len = _buf_len
    else:
      values_arr = (ctypes.c_int64 * len(values))(*values)
      values_ptr = values_arr
      values_len = len(values)
    r = self._sumSeq(values_ptr, values_len)
    _check_error()
    return r

  _makePointList = _lib.makePointList
  _makePointList.argtypes = [ctypes.c_int64]
  _makePointList.restype = ctypes.c_void_p
  def makePointList(self, n: int) -> List['Point']:
    r = self._makePointList(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    out = [_struct_unpack_plain('Point', r, 16, _struct_size('Point'), i) for i in range(n)]
    _lib.ocheFreeDeep(r); return out

  _makeUserList = _lib.makeUserList
  _makeUserList.argtypes = [ctypes.c_int64]
  _makeUserList.restype = ctypes.c_void_p
  def makeUserList(self, n: int) -> List['User']:
    r = self._makeUserList(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    out = [_struct_unpack_plain('User', r, 16, _struct_size('User'), i) for i in range(n)]
    _lib.ocheFreeDeep(r); return out

  _getPointsView = _lib.getPointsView
  _getPointsView.argtypes = []
  _getPointsView.restype = ctypes.c_void_p
  def getPointsView(self, ) -> 'NativeListView':
    r = self._getPointsView()
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    return NativeListView(r, lambda addr: PointView(addr, owned=False), _struct_size('Point'), _lib.ocheFreeDeep, numpy_dtype=_NUMPY_DTYPE_Point)

  _getUsersView = _lib.getUsersView
  _getUsersView.argtypes = []
  _getUsersView.restype = ctypes.c_void_p
  def getUsersView(self, ) -> 'NativeListView':
    r = self._getUsersView()
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    return NativeListView(r, lambda addr: UserView(addr, owned=False), _struct_size('User'), _lib.ocheFreeDeep, numpy_dtype=None)

  _makeIntBuffer = _lib.makeIntBuffer
  _makeIntBuffer.argtypes = [ctypes.c_int64]
  _makeIntBuffer.restype = ctypes.c_void_p
  def makeIntBuffer(self, n: int) -> 'SharedListView':
    r = self._makeIntBuffer(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, ctypes.sizeof(ctypes.c_int64), None, 0, True, 'c_int64')

  _makeParticleBuffer = _lib.makeParticleBuffer
  _makeParticleBuffer.argtypes = [ctypes.c_int64]
  _makeParticleBuffer.restype = ctypes.c_void_p
  def makeParticleBuffer(self, n: int) -> 'SharedListView':
    r = self._makeParticleBuffer(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, _struct_size('Particle'), lambda addr: ParticleView(addr), 2, True, numpy_dtype=_NUMPY_DTYPE_Particle)

  _makeUserBuffer = _lib.makeUserBuffer
  _makeUserBuffer.argtypes = [ctypes.c_int64]
  _makeUserBuffer.restype = ctypes.c_void_p
  def makeUserBuffer(self, n: int) -> 'SharedListView':
    r = self._makeUserBuffer(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, _struct_size('User'), lambda addr: UserView(addr), 3, False, numpy_dtype=None)

  _sumIntBuffer = _lib.sumIntBuffer
  _sumIntBuffer.argtypes = [ctypes.c_void_p]
  _sumIntBuffer.restype = ctypes.c_int64
  def sumIntBuffer(self, buf: 'SharedListView') -> int:
    r = self._sumIntBuffer(buf._ptr if hasattr(buf, '_ptr') else int(buf))
    _check_error()
    return r

  _doubleIntBuffer = _lib.doubleIntBuffer
  _doubleIntBuffer.argtypes = [ctypes.c_void_p]
  _doubleIntBuffer.restype = ctypes.c_void_p
  def doubleIntBuffer(self, buf: 'SharedListView') -> 'SharedListView':
    r = self._doubleIntBuffer(buf._ptr if hasattr(buf, '_ptr') else int(buf))
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, ctypes.sizeof(ctypes.c_int64), None, 0, True, 'c_int64')

  _countActiveUsers = _lib.countActiveUsers
  _countActiveUsers.argtypes = [ctypes.c_void_p]
  _countActiveUsers.restype = ctypes.c_int64
  def countActiveUsers(self, buf: 'SharedListView') -> int:
    r = self._countActiveUsers(buf._ptr if hasattr(buf, '_ptr') else int(buf))
    _check_error()
    return r

  _multiplyArray = _lib.multiplyArray
  _multiplyArray.argtypes = [ctypes.POINTER(ctypes.c_double), ctypes.c_int64, ctypes.c_double]
  _multiplyArray.restype = ctypes.c_void_p
  def multiplyArray(self, arr: Any, factor: float) -> 'SharedListView':
    if _HAS_NUMPY and isinstance(arr, np.ndarray):
      if not arr.data.contiguous: arr = np.ascontiguousarray(arr, dtype=np.dtype('f8'))
      arr_ptr = arr.ctypes.data_as(ctypes.POINTER(ctypes.c_double))
      arr_len = len(arr)
    elif hasattr(arr, 'buffer_info'):
      _buf_ptr, _buf_len = arr.buffer_info()
      arr_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_double))
      arr_len = _buf_len
    else:
      raise TypeError('OcheArray parameter \'arr\' requires a contiguous buffer (numpy array or array.array). Got: ' + type(arr).__name__)
    r = self._multiplyArray(arr_ptr, arr_len, factor)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, ctypes.sizeof(ctypes.c_double), None, 0, True, 'c_double')

  _dotProduct = _lib.dotProduct
  _dotProduct.argtypes = [ctypes.POINTER(ctypes.c_double), ctypes.c_int64, ctypes.POINTER(ctypes.c_double), ctypes.c_int64]
  _dotProduct.restype = ctypes.c_double
  def dotProduct(self, a: Any, b: Any) -> float:
    if _HAS_NUMPY and isinstance(a, np.ndarray):
      if not a.data.contiguous: a = np.ascontiguousarray(a, dtype=np.dtype('f8'))
      a_ptr = a.ctypes.data_as(ctypes.POINTER(ctypes.c_double))
      a_len = len(a)
    elif hasattr(a, 'buffer_info'):
      _buf_ptr, _buf_len = a.buffer_info()
      a_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_double))
      a_len = _buf_len
    else:
      raise TypeError('OcheArray parameter \'a\' requires a contiguous buffer (numpy array or array.array). Got: ' + type(a).__name__)
    if _HAS_NUMPY and isinstance(b, np.ndarray):
      if not b.data.contiguous: b = np.ascontiguousarray(b, dtype=np.dtype('f8'))
      b_ptr = b.ctypes.data_as(ctypes.POINTER(ctypes.c_double))
      b_len = len(b)
    elif hasattr(b, 'buffer_info'):
      _buf_ptr, _buf_len = b.buffer_info()
      b_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_double))
      b_len = _buf_len
    else:
      raise TypeError('OcheArray parameter \'b\' requires a contiguous buffer (numpy array or array.array). Got: ' + type(b).__name__)
    r = self._dotProduct(a_ptr, a_len, b_ptr, b_len)
    _check_error()
    return r

  _sumIntsPtr = _lib.sumIntsPtr
  _sumIntsPtr.argtypes = [ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
  _sumIntsPtr.restype = ctypes.c_int64
  def sumIntsPtr(self, arr: Any) -> int:
    if isinstance(arr, ctypes.POINTER(ctypes.c_int64)) or isinstance(arr, ctypes.Array):
      arr_ptr = ctypes.cast(arr, ctypes.POINTER(ctypes.c_int64))
      arr_len = arr._length_ if hasattr(arr, '_length_') else ctypes.sizeof(arr) // ctypes.sizeof(ctypes.c_int64)
    elif _HAS_NUMPY and isinstance(arr, np.ndarray):
      if not arr.data.contiguous: arr = np.ascontiguousarray(arr, dtype=np.dtype('i8'))
      arr_ptr = arr.ctypes.data_as(ctypes.POINTER(ctypes.c_int64))
      arr_len = len(arr)
    elif hasattr(arr, 'buffer_info'):
      _buf_ptr, _buf_len = arr.buffer_info()
      arr_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_int64))
      arr_len = _buf_len
    else:
      raise TypeError('OchePtr parameter \'arr\' requires a ctypes pointer, numpy array, or array.array. Got: ' + type(arr).__name__)
    r = self._sumIntsPtr(arr_ptr, arr_len)
    _check_error()
    return r

  _negateIntsPtr = _lib.negateIntsPtr
  _negateIntsPtr.argtypes = [ctypes.POINTER(ctypes.c_int64), ctypes.c_int64]
  _negateIntsPtr.restype = ctypes.c_void_p
  def negateIntsPtr(self, arr: Any) -> 'SharedListView':
    if isinstance(arr, ctypes.POINTER(ctypes.c_int64)) or isinstance(arr, ctypes.Array):
      arr_ptr = ctypes.cast(arr, ctypes.POINTER(ctypes.c_int64))
      arr_len = arr._length_ if hasattr(arr, '_length_') else ctypes.sizeof(arr) // ctypes.sizeof(ctypes.c_int64)
    elif _HAS_NUMPY and isinstance(arr, np.ndarray):
      if not arr.data.contiguous: arr = np.ascontiguousarray(arr, dtype=np.dtype('i8'))
      arr_ptr = arr.ctypes.data_as(ctypes.POINTER(ctypes.c_int64))
      arr_len = len(arr)
    elif hasattr(arr, 'buffer_info'):
      _buf_ptr, _buf_len = arr.buffer_info()
      arr_ptr = ctypes.cast(_buf_ptr, ctypes.POINTER(ctypes.c_int64))
      arr_len = _buf_len
    else:
      raise TypeError('OchePtr parameter \'arr\' requires a ctypes pointer, numpy array, or array.array. Got: ' + type(arr).__name__)
    r = self._negateIntsPtr(arr_ptr, arr_len)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, ctypes.sizeof(ctypes.c_int64), None, 0, True, 'c_int64')

  _riskyDivide = _lib.riskyDivide
  _riskyDivide.argtypes = [ctypes.c_int64, ctypes.c_int64]
  _riskyDivide.restype = ctypes.c_int64
  def riskyDivide(self, a: int, b: int) -> int:
    r = self._riskyDivide(a, b)
    _check_error()
    return r

  _riskyUser = _lib.riskyUser
  _riskyUser.argtypes = [ctypes.c_char_p]
  _riskyUser.restype = ctypes.c_void_p
  def riskyUser(self, name: str) -> 'User':
    r = self._riskyUser(name.encode('utf-8') if name else None)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['User']
    _ct = _struct_types['User'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['User']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)

  _resetPoint = _lib.resetPoint
  _resetPoint.argtypes = [ctypes.c_void_p]
  _resetPoint.restype = ctypes.c_void_p
  def resetPoint(self, p: Union['Point', 'PointView']) -> 'Point':
    p_buf = _pack_struct('Point', p) if p is not None else None
    r = self._resetPoint(ctypes.byref(p_buf) if p_buf is not None else None)
    _check_error()
    if r is None: return None
    _plain_cls = _struct_plain_types['Point']
    _ct = _struct_types['Point'].from_address(ctypes.cast(r, ctypes.c_void_p).value)
    _meta = _struct_field_meta['Point']
    _kwargs = {}
    for _fn, _ft in _ct._fields_:
      _raw = getattr(_ct, _fn)
      _kind, _extra = _meta.get(_fn, ('pod', None))
      if _kind == 'string':
        _kwargs[_fn] = ctypes.string_at(_raw).decode('utf-8') if _raw else None
      elif _kind == 'struct':
        _sv = _struct_view_types[_extra](ctypes.addressof(getattr(_ct, _fn)), owned=False)
        _kwargs[_fn] = _struct_plain_types[_extra]._from_view(_sv)
      else:
        _kwargs[_fn] = _raw
    _lib.ocheFree(r)
    return _plain_cls(**_kwargs)


porche = Porche()
