# ------------------ Generated by Porche ------------------
#              Don't edit this file by hand!
# -----------------------------------------------------------
from typing import Optional, Any, List
import ctypes
import os

try:
  import numpy as np
  _HAS_NUMPY = True
except ImportError:
  _HAS_NUMPY = False

_struct_size_cache = {}
_struct_types = {}
def _struct_size(name):
  return _struct_size_cache.get(name, 8)

def _pack_struct(name, obj):
  if obj is None: return None
  t = _struct_types[name]
  if hasattr(obj, '_as_buffer'): return obj
  buf = t()
  for (k, v) in (obj.items() if hasattr(obj, 'items') else obj):
    setattr(buf, k, v)
  return buf

def _unpack_struct(name, ptr, offset, elem_size, index):
  t = _struct_types[name]
  p = ctypes.cast(ctypes.c_void_p(ctypes.addressof(ctypes.cast(ptr, ctypes.POINTER(ctypes.c_char)).contents) + offset + index * elem_size), ctypes.POINTER(t))
  return _struct_from_ctypes(name, p.contents)

def _struct_from_ctypes(name, c):
  d = {}
  for (fname, _) in c._fields_:
    d[fname] = getattr(c, fname)
  return d

class _SharedView:
  def __init__(self, ptr, n, elem_size, struct_name, free_fn, type_id=0, is_pod=True, elem_ctype=None, dtype=None):
    self._ptr = ptr
    self._n = n
    self._elem_size = elem_size
    self._struct_name = struct_name
    self._free_fn = free_fn
    self._type_id = type_id
    self._is_pod = is_pod
    self._elem_ctype = getattr(ctypes, elem_ctype) if isinstance(elem_ctype, str) else elem_ctype
    self._dtype = dtype
  def __len__(self): return self._n
  def __getitem__(self, i):
    if self._struct_name:
      return _unpack_struct(self._struct_name, self._ptr, 16, self._elem_size, i)
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    return ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value
  def __setitem__(self, i, v):
    if i < 0 or i >= self._n: raise IndexError('Index out of range')
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._struct_name:
      # Free inner if not POD
      if not self._is_pod:
        _ocheFreeInner(ctypes.c_void_p(addr), self._type_id)
      # Pack the new struct
      if hasattr(v, '_as_buffer'):
        ctypes.memmove(addr, v._as_buffer, self._elem_size)
      else:
        buf = _pack_struct(self._struct_name, v)
        ctypes.memmove(addr, ctypes.addressof(buf), self._elem_size)
    else:
      # For primitives
      ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value = v
  def __del__(self):
    if self._ptr is not None and self._free_fn: self._free_fn(self._ptr)
  def to_numpy(self):
    # convert shared buffer into a NumPy array if possible
    if not _HAS_NUMPY:
      return None
    data_addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16
    if self._struct_name:
      # when the elements are structs we can still create a structured dtype
      t = _struct_types.get(self._struct_name)
      if t is None:
        return None
      try:
        dt = np.dtype(t)
      except Exception:
        return None
      buf = (ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr)
      return np.frombuffer(buf, dtype=dt, count=self._n)
    # primitive array path
    if self._dtype:
      return np.frombuffer((ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr), dtype=self._dtype, count=self._n)
    return None
_lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'libmain.so')
_lib = ctypes.CDLL(_lib_path)

_lib.ocheFree.argtypes = [ctypes.c_void_p]
_lib.ocheFree.restype = None
_lib.ocheFreeDeep.argtypes = [ctypes.c_void_p]
_lib.ocheFreeDeep.restype = None
_ocheFreeInner = _lib.ocheFreeInner
_ocheFreeInner.argtypes = [ctypes.c_void_p, ctypes.c_int32]
_ocheFreeInner.restype = None
_oche_get_error = _lib.ocheGetError
_oche_get_error.restype = ctypes.c_void_p
def _check_error():
    p = _oche_get_error()
    if p is not None:
        msg = ctypes.string_at(p).decode('utf-8')
        _lib.ocheFree(p)
        raise RuntimeError('NimError: ' + msg)

class Point_t(ctypes.Structure):
  _fields_ = [
    ('x', ctypes.c_double),
    ('y', ctypes.c_double),
  ]
_struct_size_cache['Point'] = ctypes.sizeof(Point_t)
_struct_types['Point'] = Point_t

class Tag_t(ctypes.Structure):
  _fields_ = [
    ('name', ctypes.c_void_p),
    ('id', ctypes.c_int64),
  ]
_struct_size_cache['Tag'] = ctypes.sizeof(Tag_t)
_struct_types['Tag'] = Tag_t

class User_t(ctypes.Structure):
  _fields_ = [
    ('username', ctypes.c_void_p),
    ('status', ctypes.c_int32),
    ('primaryTag', ctypes.c_void_p),
  ]
_struct_size_cache['User'] = ctypes.sizeof(User_t)
_struct_types['User'] = User_t

class Status:
  Active = 0
  Inactive = 1
  Pending = 2

class Porche:
  _addNumbersPy = _lib.addNumbersPy
  _addNumbersPy.argtypes = [ctypes.c_int64, ctypes.c_int64]
  _addNumbersPy.restype = ctypes.c_int64
  def addNumbersPy(self, a: int, b: int) -> int:
    r = self._addNumbersPy(a, b)
    _check_error()
    return r

  _greetPy = _lib.greetPy
  _greetPy.argtypes = [ctypes.c_char_p]
  _greetPy.restype = ctypes.c_void_p
  def greetPy(self, name: str) -> str:
    r = self._greetPy(name.encode('utf-8') if name else None)
    _check_error()
    if r is None: return ''
    s = ctypes.string_at(r).decode('utf-8'); _lib.ocheFree(r); return s

  _createUserPy = _lib.createUserPy
  _createUserPy.argtypes = [ctypes.c_char_p, ctypes.c_int64]
  _createUserPy.restype = ctypes.c_void_p
  def createUserPy(self, name: str, tagId: int) -> Any:
    r = self._createUserPy(name.encode('utf-8') if name else None, tagId)
    _check_error()
    if r is None: return None
    sz = _struct_size('User')
    return _unpack_struct('User', r, 0, sz, 0)

  _getPointsCopyPy = _lib.getPointsCopyPy
  _getPointsCopyPy.argtypes = [ctypes.c_int64]
  _getPointsCopyPy.restype = ctypes.c_void_p
  def getPointsCopyPy(self, n: int) -> List[Any]:
    r = self._getPointsCopyPy(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    out = [_unpack_struct('Point', r, 16, _struct_size('Point'), i) for i in range(n)]
    _lib.ocheFreeDeep(r); return out

  _maybePoint = _lib.maybePoint
  _maybePoint.argtypes = [ctypes.c_int64]
  _maybePoint.restype = ctypes.c_void_p
  def maybePoint(self, which: int) -> Optional[Any]:
    r = self._maybePoint(which)
    _check_error()
    if r is None: return None
    sz = _struct_size('Point')
    out = _unpack_struct('Point', r, 0, sz, 0); _lib.ocheFree(r); return out

  _initSharedUsersPy = _lib.initSharedUsersPy
  _initSharedUsersPy.argtypes = [ctypes.c_int64]
  _initSharedUsersPy.restype = ctypes.c_void_p
  def initSharedUsersPy(self, n: int) -> List[Any]:
    r = self._initSharedUsersPy(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return _SharedView(r, n, _struct_size('User'), 'User', None, 3, False, None, 'None')


porche = Porche()
