# ------------------ Generated by Porche ------------------
#              Don't edit this file by hand!
# -----------------------------------------------------------
from typing import Optional, Any, List
import ctypes
import os

try:
  import numpy as np
  _HAS_NUMPY = True
except ImportError:
  _HAS_NUMPY = False

_struct_size_cache: dict = {}
_struct_types: dict = {}
_struct_field_meta: dict = {}

def _struct_size(name: str) -> int:
  return _struct_size_cache.get(name, 8)

# -- Copy-mode helpers --

def _pack_struct(name: str, obj):
  if obj is None: return None
  t = _struct_types[name]
  if hasattr(obj, '_as_buffer'): return obj
  buf = t()
  for (k, v) in (obj.items() if hasattr(obj, 'items') else obj):
    setattr(buf, k, v)
  return buf

def _struct_copy(name: str, ptr, offset: int, elem_size: int, index: int) -> dict:
  addr = ctypes.cast(ptr, ctypes.c_void_p).value + offset + index * elem_size
  return _struct_from_ctypes(name, _struct_types[name].from_address(addr))

_struct_view_types: dict = {}

def _struct_copy_view(name: str, ptr, offset: int, elem_size: int, index: int):
  src = ctypes.cast(ptr, ctypes.c_void_p).value + offset + index * elem_size
  dst = _lib.ocheAllocBytes(ctypes.c_size_t(elem_size))
  ctypes.memmove(dst, src, elem_size)
  view_cls = _struct_view_types.get(name)
  return view_cls(dst, owned=True) if view_cls else None

def _struct_from_ctypes(name: str, c) -> dict:
  d = {}
  meta = _struct_field_meta.get(name, {})
  for (fname, _) in c._fields_:
    raw = getattr(c, fname)
    kind, extra = meta.get(fname, ('pod', None))
    if kind == 'string':
      d[fname] = ctypes.string_at(raw).decode('utf-8') if raw else None
    elif kind == 'struct':
      d[fname] = _struct_from_ctypes(extra, raw)
    else:
      d[fname] = raw
  return d

# -- NativeListView (view mode: zero-copy, read-only) --

class NativeListView:
  __slots__ = ('_ptr', '_n', '_elem_size', '_unpacker', '_free_fn', '_elem_ctype')
  def __init__(self, ptr, unpacker, elem_size: int, free_fn, elem_ctype=None):
    self._ptr = ptr
    self._n = ctypes.cast(ptr, ctypes.POINTER(ctypes.c_int64)).contents.value if ptr else 0
    self._elem_size = elem_size
    self._unpacker = unpacker
    self._free_fn = free_fn
    self._elem_ctype = getattr(ctypes, elem_ctype) if isinstance(elem_ctype, str) else elem_ctype
  def __len__(self): return self._n
  def __getitem__(self, i):
    if i < 0 or i >= self._n: raise IndexError('index out of range')
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker: return self._unpacker(addr)
    return ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value
  def __setitem__(self, i, v):
    raise TypeError('NativeListView is read-only. Use SharedListView for mutation.')
  def __iter__(self):
    for i in range(self._n): yield self[i]
  def __del__(self):
    if self._ptr and self._free_fn: self._free_fn(self._ptr)
  def to_list(self) -> list:
    return [self[i] for i in range(self._n)]
  def to_numpy(self):
    if not _HAS_NUMPY or self._unpacker: return None
    data_addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16
    dt = np.dtype(self._elem_ctype)
    return np.frombuffer(
      (ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr),
      dtype=dt, count=self._n).copy()

# -- SharedListView (share mode: zero-copy, read-write) --

class SharedListView:
  __slots__ = ('_ptr', '_n', '_elem_size', '_unpacker', '_type_id', '_is_pod', '_elem_ctype')
  def __init__(self, ptr, n: int, elem_size: int, unpacker, type_id: int = 0,
               is_pod: bool = True, elem_ctype=None):
    self._ptr = ptr
    self._n = n
    self._elem_size = elem_size
    self._unpacker = unpacker
    self._type_id = type_id
    self._is_pod = is_pod
    self._elem_ctype = getattr(ctypes, elem_ctype) if isinstance(elem_ctype, str) else elem_ctype
  def __len__(self): return self._n
  def __getitem__(self, i):
    if i < 0 or i >= self._n: raise IndexError('index out of range')
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker: return self._unpacker(addr)
    return ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value
  def __setitem__(self, i, v):
    if i < 0 or i >= self._n: raise IndexError('index out of range')
    addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16 + i * self._elem_size
    if self._unpacker:
      if not self._is_pod: _ocheFreeInner(ctypes.c_void_p(addr), self._type_id)
      if hasattr(v, '_addr'):
        ctypes.memmove(addr, v._addr, self._elem_size)
      else:
        struct_name = None
        for sn, st in _struct_types.items():
          if ctypes.sizeof(st) == self._elem_size: struct_name = sn; break
        if struct_name is None:
          raise TypeError(f'Cannot infer struct type for SharedListView elem_size={self._elem_size}')
        buf = _pack_struct(struct_name, v)
        ctypes.memmove(addr, ctypes.addressof(buf), self._elem_size)
    else:
      ctypes.cast(addr, ctypes.POINTER(self._elem_ctype)).contents.value = v
  def __iter__(self):
    for i in range(self._n): yield self[i]
  def to_list(self) -> list:
    return [self[i] for i in range(self._n)]
  def free(self):
    if self._ptr:
      _lib.ocheFreeDeep(self._ptr)
      self._ptr = None
      self._n = 0
  def __enter__(self): return self
  def __exit__(self, *_): self.free()
  def to_numpy(self):
    if not _HAS_NUMPY or self._unpacker: return None
    data_addr = ctypes.cast(self._ptr, ctypes.c_void_p).value + 16
    dt = np.dtype(self._elem_ctype)
    return np.frombuffer(
      (ctypes.c_char * (self._n * self._elem_size)).from_address(data_addr),
      dtype=dt, count=self._n)

_lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'libmain.so')
_lib = ctypes.CDLL(_lib_path)

_lib.ocheFree.argtypes = [ctypes.c_void_p]
_lib.ocheFree.restype = None
_lib.ocheFreeDeep.argtypes = [ctypes.c_void_p]
_lib.ocheFreeDeep.restype = None
_ocheFreeInner = _lib.ocheFreeInner
_ocheFreeInner.argtypes = [ctypes.c_void_p, ctypes.c_int32]
_ocheFreeInner.restype = None
_lib.ocheAllocBytes.argtypes = [ctypes.c_size_t]
_lib.ocheAllocBytes.restype = ctypes.c_void_p
_oche_get_error = _lib.ocheGetError
_oche_get_error.restype = ctypes.c_void_p
def _check_error():
    p = _oche_get_error()
    if p is not None:
        msg = ctypes.string_at(p).decode('utf-8')
        _lib.ocheFree(p)
        raise RuntimeError('NimError: ' + msg)

class Point_t(ctypes.Structure):
  _fields_ = [
    ('x', ctypes.c_double),
    ('y', ctypes.c_double),
  ]
_struct_size_cache['Point'] = ctypes.sizeof(Point_t)
_struct_types['Point'] = Point_t
_struct_field_meta['Point'] = {
  'x': ('pod', None),
  'y': ('pod', None),
}
_OFF_Point_x = Point_t.x.offset
_OFF_Point_y = Point_t.y.offset
class PointView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def x(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Point_x).value
  @x.setter
  def x(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Point_x).value = v
  @property
  def y(self) -> float:
    return ctypes.c_double.from_address(self._addr + _OFF_Point_y).value
  @y.setter
  def y(self, v: float):
    ctypes.c_double.from_address(self._addr + _OFF_Point_y).value = v
  def to_dict(self) -> dict:
    return _struct_from_ctypes('Point', Point_t.from_address(self._addr))
  def __repr__(self):
    return 'PointView(' + str(self.to_dict()) + ')'
_struct_view_types['Point'] = PointView

class Tag_t(ctypes.Structure):
  _fields_ = [
    ('name', ctypes.c_void_p),
    ('id', ctypes.c_int64),
  ]
_struct_size_cache['Tag'] = ctypes.sizeof(Tag_t)
_struct_types['Tag'] = Tag_t
_struct_field_meta['Tag'] = {
  'name': ('string', None),
  'id': ('pod', None),
}
_OFF_Tag_name = Tag_t.name.offset
_OFF_Tag_id = Tag_t.id.offset
class TagView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def name(self) -> Optional[str]:
    p = ctypes.c_void_p.from_address(self._addr + _OFF_Tag_name).value
    return ctypes.string_at(p).decode('utf-8') if p else None
  @property
  def id(self) -> int:
    return ctypes.c_int64.from_address(self._addr + _OFF_Tag_id).value
  @id.setter
  def id(self, v: int):
    ctypes.c_int64.from_address(self._addr + _OFF_Tag_id).value = v
  def to_dict(self) -> dict:
    return _struct_from_ctypes('Tag', Tag_t.from_address(self._addr))
  def __repr__(self):
    return 'TagView(' + str(self.to_dict()) + ')'
_struct_view_types['Tag'] = TagView

class User_t(ctypes.Structure):
  _fields_ = [
    ('username', ctypes.c_void_p),
    ('status', ctypes.c_int32),
    ('primaryTag', Tag_t),
  ]
_struct_size_cache['User'] = ctypes.sizeof(User_t)
_struct_types['User'] = User_t
_struct_field_meta['User'] = {
  'username': ('string', None),
  'status': ('pod', None),
  'primaryTag': ('struct', 'Tag'),
}
_OFF_User_username = User_t.username.offset
_OFF_User_status = User_t.status.offset
_OFF_User_primaryTag = User_t.primaryTag.offset
class UserView:
  __slots__ = ('_addr', '_owned')
  def __init__(self, addr: int, owned: bool = False):
    self._addr = addr
    self._owned = owned
  def __del__(self):
    if self._owned and self._addr:
      _lib.ocheFree(ctypes.c_void_p(self._addr))
      self._addr = 0
  @property
  def username(self) -> Optional[str]:
    p = ctypes.c_void_p.from_address(self._addr + _OFF_User_username).value
    return ctypes.string_at(p).decode('utf-8') if p else None
  @property
  def status(self) -> int:
    return ctypes.c_int32.from_address(self._addr + _OFF_User_status).value
  @status.setter
  def status(self, v: int):
    ctypes.c_int32.from_address(self._addr + _OFF_User_status).value = int(v)
  @property
  def primaryTag(self) -> 'TagView':
    return TagView(self._addr + _OFF_User_primaryTag, owned=False)
  def to_dict(self) -> dict:
    return _struct_from_ctypes('User', User_t.from_address(self._addr))
  def __repr__(self):
    return 'UserView(' + str(self.to_dict()) + ')'
_struct_view_types['User'] = UserView

class Status:
  Active = 0
  Inactive = 1
  Pending = 2

class Porche:
  _addNumbersPy = _lib.addNumbersPy
  _addNumbersPy.argtypes = [ctypes.c_int64, ctypes.c_int64]
  _addNumbersPy.restype = ctypes.c_int64
  def addNumbersPy(self, a: int, b: int) -> int:
    r = self._addNumbersPy(a, b)
    _check_error()
    return r

  _greetPy = _lib.greetPy
  _greetPy.argtypes = [ctypes.c_char_p]
  _greetPy.restype = ctypes.c_void_p
  def greetPy(self, name: str) -> str:
    r = self._greetPy(name.encode('utf-8') if name else None)
    _check_error()
    if r is None: return ''
    s = ctypes.string_at(r).decode('utf-8'); _lib.ocheFree(r); return s

  _createUserPy = _lib.createUserPy
  _createUserPy.argtypes = [ctypes.c_char_p, ctypes.c_int64]
  _createUserPy.restype = ctypes.c_void_p
  def createUserPy(self, name: str, tagId: int) -> 'UserView':
    r = self._createUserPy(name.encode('utf-8') if name else None, tagId)
    _check_error()
    if r is None: return None
    sz = _struct_size('User')
    dst = _lib.ocheAllocBytes(ctypes.c_size_t(sz))
    ctypes.memmove(dst, r, sz)
    _lib.ocheFree(r)
    return UserView(dst, owned=True)

  _getPointsCopyPy = _lib.getPointsCopyPy
  _getPointsCopyPy.argtypes = [ctypes.c_int64]
  _getPointsCopyPy.restype = ctypes.c_void_p
  def getPointsCopyPy(self, n: int) -> List['PointView']:
    r = self._getPointsCopyPy(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: _lib.ocheFreeDeep(r); return []
    out = [_struct_copy_view('Point', r, 16, _struct_size('Point'), i) for i in range(n)]
    _lib.ocheFreeDeep(r); return out

  _maybePoint = _lib.maybePoint
  _maybePoint.argtypes = [ctypes.c_int64]
  _maybePoint.restype = ctypes.c_void_p
  def maybePoint(self, which: int) -> Optional[Any]:
    r = self._maybePoint(which)
    _check_error()
    if r is None: return None
    sz = _struct_size('Point')
    out = _struct_copy('Point', r, 0, sz, 0); _lib.ocheFree(r); return out

  _initSharedUsersPy = _lib.initSharedUsersPy
  _initSharedUsersPy.argtypes = [ctypes.c_int64]
  _initSharedUsersPy.restype = ctypes.c_void_p
  def initSharedUsersPy(self, n: int) -> 'SharedListView':
    r = self._initSharedUsersPy(n)
    _check_error()
    if r is None: return []
    n = ctypes.cast(r, ctypes.POINTER(ctypes.c_int64)).contents.value
    if n <= 0: return []
    return SharedListView(r, n, _struct_size('User'), lambda addr: UserView(addr), 3, False)


porche = Porche()
