//------------------ Generated by Oche ------------------
//              Don't edit this file by hand!
// ------------------------------------------------------
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;
import 'dart:collection';
import 'package:ffi/ffi.dart';

final String _libName = Platform.isWindows ? 'lib???.dll' : (Platform.isMacOS ? 'lib???.dylib' : 'lib???.so');
final dynlib = ffi.DynamicLibrary.open('./$_libName');
final _ocheFree = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer), void Function(ffi.Pointer)>('ocheFree');
final _ocheFreeDeep = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer), void Function(ffi.Pointer)>('ocheFreeDeep');
final _ocheFreeInner = dynlib.lookupFunction<ffi.Void Function(ffi.Pointer, ffi.Int32), void Function(ffi.Pointer, int)>('ocheFreeInner');
final _ocheGetError = dynlib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('ocheGetError');
void _checkError() { final ptr = _ocheGetError(); if (ptr.address != 0) { final msg = ptr.toDartString(); _ocheFree(ptr); throw Exception('NimError: $msg'); } }
final class NUser extends ffi.Struct {
  @ffi.Int64() external int id;
  external ffi.Pointer<Utf8> name;
}

extension type UserView(NUser _ref) {
  int get id => _ref.id;
  set id(int v) => _ref.id = v;
  String get name => (_ref.name.address == 0) ? '' : _ref.name.toDartString();
  void _packInto(ffi.Pointer<NUser> p) {
    p.ref.id = _ref.id;
    p.ref.name = _ref.name;
  }
}

class User {
  final int id;
  final String name;
  const User({
    required this.id,
    required this.name
  });

  void _pack(NUser target, ffi.Allocator alloc) {
    target.id = id;
    target.name = name.toNativeUtf8(allocator: alloc);
  }

  void _packManual(NUser target) {
    target.id = id;
    target.name = name.toNativeUtf8(allocator: malloc);
  }

  static User _unpack(NUser source) {
    return User(
    id: source.id,
    name: (source.name.address == 0) ? '' : source.name.toDartString(),
    );
  }
}
typedef NinitUserN = ffi.Pointer<NUser> Function(ffi.Int64, ffi.Pointer<Utf8>);
typedef NinitUserD = ffi.Pointer<NUser> Function(int, ffi.Pointer<Utf8>);
typedef NpnameN = ffi.Void Function(ffi.Pointer<NUser>);
typedef NpnameD = void Function(ffi.Pointer<NUser>);
final _finalizerDeep = Finalizer<ffi.Pointer<ffi.Void>>((ptr) => _ocheFreeDeep(ptr));

abstract class OcheView<T> extends ListBase<T> {
  ffi.Pointer<ffi.Void> get _nativePtr;
  @override int get length;
  @override set length(int value) => throw UnsupportedError('Cannot resize native buffer');
  @override Iterator<T> get iterator => _NativeListIterator<T>(this);
}

class NativeListView<T> extends OcheView<T> {
  ffi.Pointer<ffi.Void> _ptr;
  final T Function(ffi.Pointer<ffi.Void> ptr) _unpacker;
  final int _elemSize;
  @override late final int length;
  NativeListView(this._ptr, this._unpacker, this._elemSize) {
    if (_ptr.address == 0) { length = 0; return; }
    length = ffi.Pointer<ffi.Int64>.fromAddress(_ptr.address).value;
    _finalizerDeep.attach(this, _ptr, detach: this);
  }
  @override ffi.Pointer<ffi.Void> get _nativePtr => _ptr;
  @override T operator [](int index) {
    if (_ptr.address == 0) throw StateError('NativeListView has been disposed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    return _unpacker(ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize)));
  }
  @override void operator []=(int index, T value) => throw UnsupportedError('View mode is read-only. Use Buffer mode for mutation.');
  void dispose() {
    if (_ptr.address == 0) return;
    _finalizerDeep.detach(this);
    _ocheFreeDeep(_ptr);
    _ptr = ffi.Pointer.fromAddress(0);
  }
}

class SharedListView<T> extends OcheView<T> {
  final ffi.Pointer<ffi.Void> _ptr;
  final T Function(ffi.Pointer<ffi.Void> ptr) _unpacker;
  final void Function(ffi.Pointer<ffi.Void> ptr, dynamic value)? _packer;
  final int _elemSize;
  @override late final int length;
  SharedListView(this._ptr, this._unpacker, this._packer, this._elemSize) {
    if (_ptr.address == 0) { length = 0; return; }
    length = ffi.Pointer<ffi.Int64>.fromAddress(_ptr.address).value;
  }
  @override ffi.Pointer<ffi.Void> get _nativePtr => _ptr;
  @override T operator [](int index) {
    if (_ptr.address == 0) throw StateError('SharedListView has been disposed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    return _unpacker(ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize)));
  }
  @override void operator []=(int index, dynamic value) {
    if (_ptr.address == 0) throw StateError('SharedListView has been disposed');
    if (index < 0 || index >= length) throw RangeError.index(index, this);
    final flags = ffi.Pointer<ffi.Int32>.fromAddress(_ptr.address + 12).value;
    if ((flags & 1) != 0) throw StateError('Buffer is frozen (READ-ONLY)');
    final p = ffi.Pointer<ffi.Void>.fromAddress(_ptr.address + 16 + (index * _elemSize));
    if (_packer != null) { _packer!(p, value); }
    else if (value is int) { ffi.Pointer<ffi.Int64>.fromAddress(p.address).value = value; }
    else if (value is double) { ffi.Pointer<ffi.Double>.fromAddress(p.address).value = value; }
    else if (value is bool) { ffi.Pointer<ffi.Bool>.fromAddress(p.address).value = value; }
    else { throw UnsupportedError('Mutation via []= not supported for this type.'); }
  }
}

class _NativeListIterator<T> implements Iterator<T> {
  final OcheView<T> _view; int _index = -1;
  _NativeListIterator(this._view);
  @override T get current => _view[_index];
  @override bool moveNext() => ++_index < _view.length;
}
class Oche {
  late final ninitUserCall = dynlib.lookupFunction<NinitUserN, NinitUserD>('initUser');

  User initUser(final int v_id, final String v_name) {
    return using((alloc) {

      final p = ninitUserCall(v_id, v_name.toNativeUtf8(allocator: alloc)); _checkError();
      try { return User._unpack(p.ref); } finally { _ocheFree(p); }
    });
  }
  late final npnameCall = dynlib.lookupFunction<NpnameN, NpnameD>('pname');

  void pname(final User v_u) {
    return using((alloc) {
    final _v_uPtr = alloc.allocate<NUser>(ffi.sizeOf<NUser>());
    v_u._pack(_v_uPtr.ref, alloc);
      npnameCall(_v_uPtr); _checkError();
    });
  }

}
final oche = Oche();
